CREATE TABLE IF NOT EXISTS "employee_work_schedule" (
  "id" BIGSERIAL PRIMARY KEY,
  "users_id" BIGINT NOT NULL UNIQUE,
  "tolerancia_entrada" INTEGER DEFAULT 5,
  "intervalo_almoco_min" INTEGER DEFAULT 60,
  "seg_ativo" BOOLEAN NOT NULL DEFAULT true,
  "seg_entrada" VARCHAR(5),
  "seg_saida" VARCHAR(5),
  "ter_ativo" BOOLEAN NOT NULL DEFAULT true,
  "ter_entrada" VARCHAR(5),
  "ter_saida" VARCHAR(5),
  "qua_ativo" BOOLEAN NOT NULL DEFAULT true,
  "qua_entrada" VARCHAR(5),
  "qua_saida" VARCHAR(5),
  "qui_ativo" BOOLEAN NOT NULL DEFAULT true,
  "qui_entrada" VARCHAR(5),
  "qui_saida" VARCHAR(5),
  "sex_ativo" BOOLEAN NOT NULL DEFAULT true,
  "sex_entrada" VARCHAR(5),
  "sex_saida" VARCHAR(5),
  "sab_ativo" BOOLEAN NOT NULL DEFAULT false,
  "sab_entrada" VARCHAR(5),
  "sab_saida" VARCHAR(5),
  "dom_ativo" BOOLEAN NOT NULL DEFAULT false,
  "dom_entrada" VARCHAR(5),
  "dom_saida" VARCHAR(5),
  "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
  CONSTRAINT "employee_work_schedule_users_id_fkey" FOREIGN KEY ("users_id") REFERENCES "users"("id") ON UPDATE NO ACTION
);
